### ISSUE TITLE
Next Project Milestone Tasks 

### ISSUE THREAD

**Issue by ebeshero** [ceq5032/ComicBookTWD#1]
- [x] @MystKitteh will assemble individual URLs that open for each image. Also let's test to make sure those hope in an `<img src="......"/>` element. 
- [x] @MystKitteh to explore some XSLT 
- [x] @TylerDollard Look up information on the authors / illustrators and add to the XML `<metadata>` section we created. 
- [x] @TylerDollard Write some information about the comic on the website. 
- [x] @ceq5032 You did so much the previous week! Review our changes to the schema and markup, and check in on the other two!
